In [5]:
import numpy as np
arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr2=np.array([[9, 8, 7, 4],[3, 12, 4, 8]])
arr3=arr1+arr2
print("Matrix A= ",arr1)
print("Matrix B= ",arr2)
print("Addition of two matrices: ",arr3)
arr4=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
arr5=np.array([[[16,17,18],[15,16,17]],[[3,4,5],[7,8,9]]])
arr6=arr4+arr5
print("Matrix C= ",arr4)
print("Matrix D= ",arr5)
print("Addition of two matrices= ",arr6)

Matrix A=  [[1 2 3 4]
 [5 6 7 8]]
Matrix B=  [[ 9  8  7  4]
 [ 3 12  4  8]]
Addition of two matrices:  [[10 10 10  8]
 [ 8 18 11 16]]
Matrix C=  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
Matrix D=  [[[16 17 18]
  [15 16 17]]

 [[ 3  4  5]
  [ 7  8  9]]]
Addition of two matrices=  [[[17 19 21]
  [19 21 23]]

 [[ 9 11 13]
  [16 18 20]]]
